from tkinter import *
w=Tk()
w.title("Calculater")
v=StringVar()
def display(x):
    t=v.get()
    v.set(t+x)
def equal():
    t=v.get()
    e=eval(t)
    v.set(e)
def clear():
    v.set("")
def bs():
    t=v.get()
    v.set(t[0:-1])
def percent():
    t=v.get()
    p=int(t)
    v.set(p/100)
B1=Button(w,text="1",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("1"))
B2=Button(w,text="2",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("2"))
B3=Button(w,text="3",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("3"))
B4=Button(w,text="4",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("4"))
B5=Button(w,text="5",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("5"))
B6=Button(w,text="6",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("6"))
B7=Button(w,text="7",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("7"))
B8=Button(w,text="8",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("8"))
B9=Button(w,text="9",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("9"))
B0=Button(w,text="0",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("0"))
Ba=Button(w,text="+",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("+"))
Bs=Button(w,text="-",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("-"))
Bm=Button(w,text="*",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("*"))
Bd=Button(w,text="/",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("/"))
Bl=Button(w,text="%",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:percent())
Be=Button(w,text="=",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:equal())
Bc=Button(w,text="C",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=150,bd=10,command=lambda:clear())
Bp=Button(w,text=".",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:display("."))
Bb=Button(w,text="<-",font=("Edwardian Script ITC Regular",45,"bold"),padx=5,pady=5,bd=10,command=lambda:bs())
E=Entry(w,bg='light green',font=("Edwardian Script ITC Regular",45,"bold"),textvariable=v,width=15,bd=10)
E.grid(row=1,columnspan=6)
B1.grid(row=4,column=1)
Bl.grid(row=5,column=5)
B2.grid(row=4,column=2)
B3.grid(row=4,column=3)
B4.grid(row=3,column=1)
B5.grid(row=3,column=2)
B6.grid(row=3,column=3)
B7.grid(row=2,column=1)
B8.grid(row=2,column=2)
B9.grid(row=2,column=3)
B0.grid(row=5,column=2)
Ba.grid(row=2,column=4)
Bs.grid(row=4,column=4)
Bm.grid(row=3,column=4)
Bd.grid(row=5,column=4)
Be.grid(row=5,column=3)
Bp.grid(row=5,column=1)
Bc.grid(row=2,column=5,rowspan=3)
Bb.grid(row=4,column=5)
E.grid(row=1,columnspan=6)
w.mainloop()
